apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: public.ecr.aws/n5h8m9x0/pc1
        ports:
        - containerPort: 3550
        env:
        - name: MONGODB_URI
          # TODO change <MONGO_PRIMARY_DNS> bellow
          value: mongodb://mongo-0.mongo-service:27017/?replicaSet=myReplicaSet
        - name: MONGODB_PRODUCTS_DB_NAME
          value: myddd
        - name: MONGODB_PRODUCTS_COLLECTION_NAME
          value: products
        - name: PORT
          value: "3550"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: 3550
        livenessProbe:
          grpc:
            port: 3550
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
